#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Assemble the paper's tables from whatever results exist.

Two outputs.

``paper/tables_<scale>.tex`` concatenates the LaTeX fragments each experiment
wrote, in the order the paper uses them, so the manuscript can ``\\input`` a
single file.

``results/FINDINGS_<scale>.md`` is a digest: for every experiment that ran, the
handful of numbers a co-author would want to see before reading anything else,
pulled from the manifests and summaries rather than retyped. It exists because
the failure mode of a suite this size is that nobody looks at the output.

Missing experiments are skipped with a note; this script never fails because a
run is partial.
"""
from __future__ import annotations

import glob
import json
import os
import sys

import pandas as pd

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RESULTS = os.environ.get("RESULTS_DIR", os.path.join(HERE, "results"))
PAPER = os.path.join(HERE, "paper")

ORDER = [
    ("EXP-01-LANDSCAPE", "landscape.tex", "Does the radius matter?"),
    ("EXP-02-BASELINES", "baselines.tex", "Reference configurations"),
    ("EXP-03-CVPROXY", "cvproxy.tex", "Is CV a good proxy for the truth?"),
    ("EXP-06-ENSEMBLE", "ensemble.tex", "Dependence on ensemble size"),
    ("EXP-07-KRADII", "kradii.tex", "How many radii should be estimated?"),
    ("EXP-11-SMOOTHER", "smoother.tex", "Augmented smoother criterion"),
    ("EXP-09-CYCLES", "cycles.tex", "Consecutive cycles, moving network"),
    ("EXP-08-HETERO", "hetero.tex", "Heterogeneous domains"),
    ("EXP-04-META", "metaheuristics.tex", "Comparison of searches, tapered"),
    ("EXP-10-CHOLESKY", "cholesky.tex", "Comparison of searches, Cholesky"),
    ("EXP-05-BUDGET", "budget.tex", "Budget and population size"),
    ("EXP-00-TUNING", "tuning.tex", "Hyperparameter calibration"),
]


def read_manifest(exp_id, scale):
    p = os.path.join(RESULTS, f"{exp_id}_{scale}", "manifest.json")
    if not os.path.exists(p):
        return None
    try:
        with open(p) as fh:
            return json.load(fh)
    except Exception:
        return None


def read_summary(exp_id, scale):
    p = os.path.join(RESULTS, f"{exp_id}_{scale}", "summary.csv")
    if not os.path.exists(p):
        return None
    try:
        return pd.read_csv(p)
    except Exception:
        return None


def build_tex(scale):
    os.makedirs(PAPER, exist_ok=True)
    out = [f"% Tables for the CV-localization paper, scale = {scale}.",
           "% Generated by scripts/make_tables.py. Do not edit by hand.", ""]
    n = 0
    for exp_id, fname, caption in ORDER:
        p = os.path.join(RESULTS, f"{exp_id}_{scale}", "tables", fname)
        if not os.path.exists(p):
            out.append(f"% [{exp_id}] missing: {fname}")
            continue
        with open(p) as fh:
            out.append(f"% ---------- {exp_id}: {caption} ----------")
            out.append(fh.read())
            n += 1
    dest = os.path.join(PAPER, f"tables_{scale}.tex")
    with open(dest, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {dest}  ({n} tables)")
    return n


def fmt(x, nd=3):
    try:
        return f"{float(x):.{nd}f}"
    except Exception:
        return str(x)


def build_findings(scale):
    lines = [f"# Findings, scale = {scale}", "",
             "Generated by `scripts/make_tables.py` from the manifests and "
             "summaries. Every number below is traceable to the experiment "
             "directory named beside it.", ""]

    for exp_id, _, caption in ORDER:
        man = read_manifest(exp_id, scale)
        if man is None:
            continue
        summ = man.get("summary", {})
        lines.append(f"## {exp_id} - {caption}")
        lines.append(f"*{man.get('description', '').strip()}*")
        lines.append("")
        lines.append(f"- ran in {man.get('elapsed_s', '?')} s "
                     f"({man.get('finished_at', '?')})")

        if exp_id == "EXP-01-LANDSCAPE" and summ:
            lines += [
                f"- the analysis error varies by "
                f"**{fmt(summ.get('mean_spread_pct'), 1)}%** of its minimum "
                f"across the admissible range",
                f"- truth-based radius {fmt(summ.get('mean_r_truth'), 2)}, "
                f"cross-validated {fmt(summ.get('mean_r_cv'), 2)}",
                f"- penalty of the CV choice: mean "
                f"**{fmt(summ.get('mean_penalty_pct'), 1)}%**, median "
                f"{fmt(summ.get('median_penalty_pct'), 1)}%",
                f"- width of the region within 1% of the optimum: "
                f"{fmt(summ.get('mean_flat_width'), 2)} radius units "
                f"(this is why the arg-min is a poor summary)",
            ]
        elif exp_id == "EXP-03-CVPROXY" and summ:
            lines += [
                f"- penalty: mean **{fmt(summ.get('mean_penalty_pct'), 1)}%**, "
                f"median {fmt(summ.get('median_penalty_pct'), 1)}%",
                f"- rank correlation between the two curves: "
                f"{fmt(summ.get('mean_spearman'), 3)}",
            ]
        elif exp_id == "EXP-07-KRADII" and summ:
            v = summ.get("verdicts", {})
            lines.append("- verdicts over the (factor, K) cells with K > 1:")
            for k, c in sorted(v.items(), key=lambda kv: -kv[1]):
                lines.append(f"  - `{k}`: {c}")
            lines.append("  - *`search fails` means the attained J rose above "
                         "its K=1 value, which is impossible for a working "
                         "search since K=1 is nested inside every larger K.*")
        elif exp_id == "EXP-10-CHOLESKY" and summ:
            lines += [
                f"- the integer landscape has "
                f"**{fmt(summ.get('mean_local_minima'), 1)}** interior local "
                f"minima on average, so it is not unimodal",
                f"- penalty of the CV choice here: "
                f"{fmt(summ.get('mean_penalty_pct'), 1)}%",
            ]
        elif exp_id == "EXP-11-SMOOTHER" and summ:
            lines += [
                f"- criterion penalty: mean "
                f"**{fmt(summ.get('mean_penalty'), 1)}%**, median "
                f"{fmt(summ.get('median_penalty'), 1)}%",
                f"- exact agreement with the truth-based arg-min: "
                f"{fmt(100*float(summ.get('exact_rate', 0)), 0)}% of cycles",
                "  - *nothing is withheld here and the whole network is used; "
                "the score is taken on the k block against observations the "
                "analysis never assimilated.*",
            ]
        elif exp_id == "EXP-09-CYCLES" and summ:
            lines.append(f"- {summ.get('n_failed', 0)} of "
                         f"{summ.get('n_cells', '?')} runs failed")
            orc = summ.get("oracle_radius", {})
            if orc:
                lines.append(f"- oracle radius per regime: {orc}")
            best = summ.get("best_admissible", {})
            if best:
                lines.append(
                    f"- best admissible rule: **{best.get('method')}** at "
                    f"p/n={best.get('obs_ratio')} schedule={best.get('schedule')}, "
                    f"{fmt(best.get('gap_pct'), 1)}% above the oracle, with the "
                    f"radius moving {fmt(best.get('drift'), 2)} per cycle "
                    f"against {fmt(best.get('drift_raw'), 2)} for the raw "
                    f"estimate")
                lines.append("  - *the raw per-cycle estimate is not the "
                             "parameter; it is a noisy estimate of a slowly "
                             "varying one, and the gap between those two "
                             "readings is what this row measures.*")
        elif exp_id == "EXP-00-TUNING" and summ:
            frozen = summ.get("frozen", {})
            if frozen:
                lines.append("- frozen hyperparameters:")
                for opt, params in sorted(frozen.items()):
                    lines.append(f"  - `{opt}`: {params}")

        s = read_summary(exp_id, scale)
        if s is not None and len(s) <= 20:
            lines += ["", "```", s.to_string(index=False), "```"]
        lines.append("")

    dest = os.path.join(RESULTS, f"FINDINGS_{scale}.md")
    with open(dest, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {dest}")


def main():
    scale = sys.argv[1] if len(sys.argv) > 1 else os.environ.get("SCALE", "smoke")
    found = sorted(glob.glob(os.path.join(RESULTS, f"EXP-*_{scale}")))
    if not found:
        print(f"no results for scale '{scale}' under {RESULTS}; nothing to do")
        return
    build_tex(scale)
    build_findings(scale)


if __name__ == "__main__":
    main()
